# REF: https://github.com/cilium/docsearch-scraper-webhook/blob/master/.github/workflows/update-algolia-index.yaml
name: Update Algolia Index
on:
  push:
    branches:
      - master
  # Allow manual triggers.
  workflow_dispatch: {}
  # Run once a day.
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-algolia-index:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: update
      env:
        APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        echo $APPLICATION_ID
        # Based on https://docsearch.algolia.com/docs/run-your-own/
        docker run \
          -e "APPLICATION_ID=$APPLICATION_ID" \
          -e "API_KEY=$API_KEY" \
          -e "CONFIG=$(cat ./docsearch.config.json | jq -r tostring)" \
          algolia/docsearch-scraper:v1.16.0
