# REF: https://github.com/cilium/docsearch-scraper-webhook/blob/master/.github/workflows/update-algolia-index.yaml
name: Build and Deploy
on:
  push:
    branches:
      - master
  # Allow manual triggers.
  workflow_dispatch: {}
  # Run once a day.
  # schedule:
  #   - cron: "0 0 * * *"

jobs:
  build-and-deploy:
    name: Install and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - name: Test 🧪
        uses: borales/actions-yarn@v4
        with:
          cmd: test:unit
      - name: Build 🔧
        uses: borales/actions-yarn@v4
        with:
          cmd: docs:build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/.vite/dist # The folder the action should deploy.

  update-algolia-index:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
    - name: Sleep for gh-pages published 💤
      uses: jakejarvis/wait-action@master
      with:
        time: '10m'
    - name: checkout
      uses: actions/checkout@v2
    - name: update
      env:
        APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        echo $APPLICATION_ID
        # Based on https://docsearch.algolia.com/docs/run-your-own/
        docker run \
          -e "APPLICATION_ID=$APPLICATION_ID" \
          -e "API_KEY=$API_KEY" \
          -e "CONFIG=$(cat ./docsearch.config.json | jq -r tostring)" \
          algolia/docsearch-scraper:v1.16.0
